config/routes.rb
Rails.application.routes.draw do
  get '/ask', to: 'questions#ask', as: :ask
  get '/answer', to: 'questions#answer', as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Stupid Coaching</h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="quote">
  <%= @question = params[:question] %>
  <br>
  <p><em>- You</em></p>
</div>

<br>

<div class="quote answer">
  <% @question = params[:question] %>
  <% if @question.downcase == "i am going to work" %>
    <strong><%= "Great!" %></strong>
  <% elsif @question.end_with?("?") %>
    <strong><%= "Silly question, get dressed and go to work!" %></strong>
  <% else %>
    <strong><%= "I don't care, get dressed and go to work!" %></strong>
  <% end %>
  <p><em>- Your coach</em></p>
</div>

<br>

<%= link_to "Ask a new question", answer_path %>

app/views/questions/ask.html.erb
<h3>Ask your coach anything:</h3>
<form action="/answer" method="get">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>